version: '3'
services:
  # postgres
  postgres:
    # mdillon/postgis is postgres + PostGIS (only). if you need additional
    # extensions, it's probably time to create a purpose-built image with all
    # necessary extensions. sorry, and thanks for adding support for them!
    image: "mdillon/postgis:9.6"
    container_name: "typegraphqltypeorm"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "typegraphqltypeorm"
      POSTGRES_PASSWORD: "typegraphqltypeorm"
      POSTGRES_DB: "db"